[package]
name = "arc-example"
version = "0.1.0"
edition = "2021"

[dependencies]

lambda_runtime = "0.13.0"
serde = "1"
tokio = { version = "1", features = ["macros"] }
serde_json = "1.0.135"
tower = "0.4.13"
